### ISSUE TITLE
Интерфейс дисплея

### ISSUE THREAD

**Issue by kyle208** [SashaCX75/AmazFit_Watchface_Editor#11]
分辨率1920*1080（文本100%）时，预览界面下的机型无法选择，GTR47的会把其他选项挡住。
Когда разрешение составляет 1920 * 1080（Размер шрифта 100%）, модель в интерфейсе предварительного просмотра не может быть выбрана, и GTR47 заблокирует другие параметры.
![image](https://user-images.githubusercontent.com/12055155/80720310-512f4e80-8b2f-11ea-876b-7c6196fbabf1.png)

![image](https://user-images.githubusercontent.com/12055155/80720446-7b810c00-8b2f-11ea-977d-c5a0ec3818c4.png)

![image](https://user-images.githubusercontent.com/12055155/80720389-6906d280-8b2f-11ea-91c4-ca7a2ed65145.png)

**Comment by kyle208** [comment]
Некоторые пользователи сообщают, что он является 100% -ным шрифтом по умолчанию с разрешением 1920 * 1080.

**Comment by SashaCX75** [comment]
Проверил при разных разрешениях экрана и разных масштабах шрифта. У себя таких проблем не наблюдаю.
Попробую в следующей версии сделать автоматическое уменьшение панели предпросмотра если она перекрывает надписи. Но проверить не смогу потому, что у меня такох проблем нету.
![Снимок](https://user-images.githubusercontent.com/12464527/80741848-090a2f00-8b23-11ea-8b60-3148147ab03c.PNG)
![font100](https://user-images.githubusercontent.com/12464527/80741921-22ab7680-8b23-11ea-9375-45a31809af94.PNG)

**Comment by kyle208** [comment]
> Проверил при разных разрешениях экрана и разных масштабах шрифта. У себя таких проблем не наблюдаю.
> Попробую в следующей версии сделать автоматическое уменьшение панели предпросмотра если она перекрывает надписи. Но проверить не смогу потому, что у меня такох проблем нету.
> ![Снимок](https://user-images.githubusercontent.com/12464527/80741848-090a2f00-8b23-11ea-8b60-3148147ab03c.PNG)
> ![font100](https://user-images.githubusercontent.com/12464527/80741921-22ab7680-8b23-11ea-9375-45a31809af94.PNG)

我测试已经好了，谢谢
Мой тест хороший, очень хороший, спасибо

**Comment by kyle208** [comment]
AM PM 制作完成后，预览图正常，上传到手表却是无效的。显示为AM前一个序号的内容
После завершения AM PM изображение для предварительного просмотра является нормальным, но загрузка в часы недопустима. Содержимое отображается как предыдущий серийный номер AM

**Comment by SashaCX75** [comment]
@kyle208 
Из-за особенностей перевода тебя сложно понять. По возможности прикладывай скриншоты, на которых показано что неправильно работает.

На часах время отображается в 12 часовом формате (AM/PM) или в 24 часовом формате (24H). Это зависит от настроек на телефоне.

**Comment by kyle208** [comment]
Можно ли увеличить поддержку BIP.
能否增加对BIP的支持

**Comment by SashaCX75** [comment]
Нет. Поддержка  BIP не планируется. На сколько я знаю там для создания bin файла используется другая утилита и синтаксис json файла отличается.
不。 沒有計劃BIP支持。 據我所知，另一個實用程序用於創建bin文件，而json文件的語法則不同。
