### ISSUE TITLE
Change program name to explain not only for GTR

### ISSUE THREAD

**Issue by bovirus** [SashaCX75/AmazFit_Watchface_Editor#19]
@SashaCX75 

Currently by program seems that you can edit ONLY GTR Watchface.
But as you know is not true because you can change watchface for

- GTR (42)
- GTR (47)
- GTS
- T-REX
- Verge Lite

Then what do you think to change the program name to highlight that is not ONLY for GTR watchface?

You can use a program name like

AmazFit Watchface Editor

Thanks.

**Comment by SashaCX75** [comment]
I agree. The program file can be renamed. The name of the chosen model has been written in the title for a long time.
