### ISSUE TITLE
Smartwatch models in alphabetical order

### ISSUE THREAD

**Issue by bovirus** [SashaCX75/AmazFit_Watchface_Editor#20]
@SashaCX75 

What do you think to haven alphabetical order list for smartwatch model like

- GTR (42)
- GTR (47)
- GTS
- T-REX
- Verge Lite

Swap the current order for GTR(47) and GTR(42).

Thanks. KR.

**Comment by SashaCX75** [comment]
Not sure. For new users of the program, this will seem logical. But the existing users of the program are already accustomed to this arrangement of switches. And the program itself is tested on GTR 47 and on other models some of the functions do not work (on newer models the firmware is still raw and animation or weather display does not always work).

PS: The existing order is random. They are simply written in the order that their support was added to the program.

**Comment by kyle208** [comment]
I think it doesn't matter, it just feels like the order and popularity of the release. GTR’s popularity is the highest, and the others decrease in order. This order is exactly in line with my expectations.
