### ISSUE TITLE
Instruction to build source code

### ISSUE THREAD

**Issue by bovirus** [SashaCX75/AmazFit_Watchface_Editor#21]
@SashaCX75 

Could you please post here and add them in readme the instruction how to build your source code?

Requirement (Version of Visual C++ , Library,. ect)+
Instruction to build.

Thanks.

**Comment by SashaCX75** [comment]
I didn't quite understand you.
C #, .NET Framework 4.5
Additional modules: Magick.NET-Q16-AnyCPU; Newtonsoft.Json

To work with bin files are used:
resunpacker_qzip (https://github.com/amazfitbip/resunpacker_qzip)
py_amazfit_tools (https://github.com/amazfitbip/py_amazfit_tools/releases/tag/v0.2-beta)
When compiling a program, they are not needed, but for it to work they must lie next to the executable file.

Is this what you wanted?

**Comment by bovirus** [comment]
@SashaCX75 

I'd like to compile your Visual C++ source get from github reposyorty

Thanks for the info about requirements

Where can I download

Magick.NET-Q16-AnyCPU
Newtonsoft.Json

And how can install these modules?


Also could you please rebuild your program to test new Italian strings?

**Comment by SashaCX75** [comment]
In Visual Studio, I connected them via NuGet in the Links section.
![2020-07-26_14-08-09](https://user-images.githubusercontent.com/12464527/88477652-8a1e6a00-cf4a-11ea-8554-6ba7c347f635.png)

Magick.NET (https://github.com/dlemstra/Magick.NET). The program is used to create an animated gif file and apply masks to the picture.

Json.NET (https://www.newtonsoft.com/json). The program is used to work with a Json file.

In the coming days I will update the program and give a link.

If there is a desire I can give an edited help file for its translation.

**Comment by kyle208** [comment]
I probably understand what he meant, it should be to compile the source code into a runnable program. In fact, as long as you load the source code into Visual Studio, and then right-click the first one to generate it, you can compile it into a program. I compiled it like this, and moved the missing files from the files compiled by SashaCX75 into it, and it can be used normally. The directory is similar to GTR_Watch_face\GTR_Watch_face\bin\Debug
![image](https://user-images.githubusercontent.com/12055155/88492559-1f1e7300-cfde-11ea-947c-06ab22c6ae74.png)

**Comment by kyle208** [comment]
It is recommended that you transfer the branch to Animation development. Master is the most stable main branch. It is best to make your changes in Animation. Master let Sasha merge.
![image](https://user-images.githubusercontent.com/12055155/88492958-2430f180-cfe1-11ea-9e6d-12c5618a01e6.png)

**Comment by SashaCX75** [comment]
@kyle208 
Small clarification. In Debug mode, the version of the program is compressed in which the bin file cannot be created, but everything else works and you can check the correctness of the translation.

**Comment by bovirus** [comment]
@SashaCX75 

Please rebuild the dll for Italian language and update it 

here: https://amazfitwatchfaces.com/forum/viewtopic.php?t=1076&start=10

here: https://github.com/SashaCX75/GTR_Watch_face/releases

Please chenge also

GTR Watch face (**_without__Puthon_**)

in 

GTR Watch face (**_without Python_**)

**Comment by SashaCX75** [comment]
@bovirus 
https://github.com/SashaCX75/GTR_Watch_face/releases/tag/v8.4-beta
Check the translation.
In the Activity section, one phrase remained untranslated (Target steps / Цель шагов)

**Comment by kyle208** [comment]
> @bovirus
> https://github.com/SashaCX75/GTR_Watch_face/releases/tag/v8.4-beta
> Check the translation.
> In the Activity section, one phrase remained untranslated (Target steps / Цель шагов)

v8.4-beta
There is no such dll in Chinese, AmazFit_Watch_Editor.exe cannot find Chinese
На китайском нет такой dll, AmazFit_Watch_Editor.exe не может найти китайский
![image](https://user-images.githubusercontent.com/12055155/88605558-d97cab80-d0ac-11ea-8a98-ef1ee1e34e70.png)
Я вижу, вы не компилировали китайский, я перекомпилировал. Но если китайские друзья скачают у вас бета-версию, она станет русской.

**Comment by SashaCX75** [comment]
Updated the assembly. Removed unnecessary files, added missing ones.
