### ISSUE TITLE
Translation - Improve translations

### ISSUE THREAD

**Issue by bovirus** [SashaCX75/AmazFit_Watchface_Editor#22]
@SashaCX75 

I have some proposals for translation of file type box and some improvements for GUI changes.

Please remove fro build the file name "GTR_Watch_face.exe" (not ncessary)

Please rename main window caption from "GTR watch face editor" to "AmazFit wtach face editor"

Please check the screenshot if you cann edit source to localzie file type

![AmazFit wtach faxce Editor 8 4 - GUI 01](https://user-images.githubusercontent.com/1262554/88569561-e791e400-d03a-11ea-8085-408e1114f3e7.jpg)
![AmazFit wtach faxce Editor 8 4 - GUI 02](https://user-images.githubusercontent.com/1262554/88569564-e82a7a80-d03a-11ea-8a3c-c804f57e24bf.jpg)
![AmazFit wtach faxce Editor 8 4 - GUI 03](https://user-images.githubusercontent.com/1262554/88569565-e8c31100-d03a-11ea-81f4-929a221393cf.jpg)
![AmazFit wtach faxce Editor 8 4 - GUI 04](https://user-images.githubusercontent.com/1262554/88569566-e95ba780-d03a-11ea-988b-344af3dd1857.jpg)
![AmazFit wtach faxce Editor 8 4 - GUI 05](https://user-images.githubusercontent.com/1262554/88569570-e9f43e00-d03a-11ea-8d9c-9aaa292aeae8.jpg)
![AmazFit wtach faxce Editor 8 4 - GUI 06](https://user-images.githubusercontent.com/1262554/88569576-ea8cd480-d03a-11ea-89f1-c5e68396e554.jpg)
![AmazFit wtach faxce Editor 8 4 - GUI 07](https://user-images.githubusercontent.com/1262554/88569577-eb256b00-d03a-11ea-9f62-6f3f356f26e7.jpg)
![AmazFit wtach faxce Editor 8 4 - GUI 08](https://user-images.githubusercontent.com/1262554/88569580-ebbe0180-d03a-11ea-8f65-1812a0868294.jpg)
![AmazFit wtach faxce Editor 8 4 - GUI 09](https://user-images.githubusercontent.com/1262554/88569584-ebbe0180-d03a-11ea-9cd4-9705ef05470e.jpg)
![AmazFit wtach faxce Editor 8 4 - GUI 10](https://user-images.githubusercontent.com/1262554/88569587-ec569800-d03a-11ea-9a69-b6c2c11f328c.jpg)
![AmazFit wtach faxce Editor 8 4 - GUI 11](https://user-images.githubusercontent.com/1262554/88569590-ecef2e80-d03a-11ea-8e12-8adfef974be1.jpg)
![AmazFit wtach faxce Editor 8 4 - GUI 12](https://user-images.githubusercontent.com/1262554/88569593-ed87c500-d03a-11ea-917d-94ad1ddfa7cf.jpg)

Thanks.

**Comment by SashaCX75** [comment]
The GTR_Watch_face.exe file is out of date and will be removed.

The window title changes depending on the selected model.

I will expand the form with the choice of language. Initially, I didn't know what to do better, expand the form or change the spelling of Chinese to fit into the form. And then I just forgot about it.

The file types and extensions were not originally planned to be translated. If add a translation, then you need to add it for all languages. I'll think about it.

The file selection window is the standard window of the operating system. I cannot change the arrangement of elements in it.

At the expense of the new format of the list of translators, I will redo and see how it will look. Perhaps I will change it.

**Comment by SashaCX75** [comment]
![2020-07-27_20-28-52](https://user-images.githubusercontent.com/12464527/88573328-3a729800-d049-11ea-87e3-57828648cc44.png)

**Comment by bovirus** [comment]
@SashaCX75 

I beleieve that if you translate the text file type in drop down list it's an importrant step up for translation.
I believe that it's important in a trsnalted progrnm to have as much as possible not a mix of translated/not translated strings.

Strange fthink about Open/save standard dialog.
Save dialog use better GUI space then standard Open dialog.
Open Dialog not use all space in GUI available (on the left) and have short box for file name.

I will improve Italian translation.
If I can I align as strings order English and Italian language.

Thanks.

**Comment by bovirus** [comment]
@SashaCX75 

If you can move in source all strings resources under "Language" sub-folder.ex

Language\en
Language\it
etc

In this way you can have a more clear structure.

Thanks.

**Comment by SashaCX75** [comment]
@bovirus 
I myself wanted to combine all the resources into one folder, but it didn't work out.

**Comment by SashaCX75** [comment]
@bovirus 
Added the ability to translate file extensions in the selection dialog (translation is now only available in English).

**Comment by bovirus** [comment]
@SashaCX75 

What are the filds changed?
I didn't see in the repository any changes in last 2 days.

**Comment by SashaCX75** [comment]
@bovirus 
The compiled project is here (it was created 2 days ago, but the file with the archive is new there)
https://github.com/SashaCX75/AmazFit_Watchface_Editor/releases/tag/v8.4-beta

Project sources in the Animation branch
https://github.com/SashaCX75/AmazFit_Watchface_Editor/tree/Animation/GTR_Watch_face

**Comment by kyle208** [comment]
If there are no problems, you can close all issues. @bovirus

**Comment by bovirus** [comment]
@SashaCX75 

Please check the window with greetings. and my suggestion.

Please if you can before a LanguageName/author list in alphabetical order with 

LanguageName - Translation author

Then a a help language name/author list in alphabetical order with

Help LanguageName - Help language author
 
Thanks.
