### ISSUE TITLE
Chinese firmware AM/PM error

### ISSUE THREAD

**Issue by kyle208** [SashaCX75/AmazFit_Watchface_Editor#26]
The firmware in Chinese, AM/PM, always reads the first two of the AMPM serial number, so it is always wrong.
![image](https://user-images.githubusercontent.com/12055155/90959654-dec3ef00-e4ce-11ea-895c-8927c35de181.png)
The serial numbers are correct and displayed correctly in the software, but in the GTR, the images with the previous two serial numbers are displayed.

Прошивка на китайском языке, AM / PM, всегда считывает первые два серийного номера AMPM, поэтому это всегда неверно.
Серийные номера верны и правильно отображаются в программном обеспечении, но в GTR отображаются изображения с двумя предыдущими серийными номерами.

**Comment by kyle208** [comment]
![image](https://user-images.githubusercontent.com/12055155/90959768-9eb13c00-e4cf-11ea-9799-2111dc77a2b7.png)
ImageIndexAM / PMEN в официальном магазине китайских циферблатов amazfit - 0. Пожалуйста, добавьте оценку. Используется китайский перевод. По умолчанию здесь установлено значение 0, что может решить вышеуказанные проблемы.

**Comment by kyle208** [comment]
我测试了一下，好像还是会显示AM/PM的前两个图，官方的解压EN是0，那个都正常，不确定啥原因。
Я протестировал его, и кажется, что первые два изображения AM / PM все еще будут отображаться.Официальный EN декомпрессии равен 0, и это все нормально, не знаю почему.

**Comment by SashaCX75** [comment]
Я правильно тебя понял: надо если в программе выбран китайский язык, то значения AMEN и  PMEN делать равными 0. Иначе отображается не правильно.

Можешь приложить конкретный проект и фото, кок эта ошибка выглядит на часах?

我理解正確：如果在程序中選擇了中文，則應將AMEN和PMEN值設置為0.否則將顯示不正確。

您可以附加特定的項目和照片嗎，手錶上的錯誤情況如何？

**Comment by kyle208** [comment]
![image](https://user-images.githubusercontent.com/12055155/90979724-9f0e0d80-e589-11ea-89fe-77c791473e29.png)
我不确定为什么这里改了还是显示出错（pm序号显示出来的是前两个图的内容-9，am同理为8）Я не уверен, почему он был изменен или отображение неправильное (серийный номер pm показывает содержание первых двух изображений - 9, am такое же, как 8)

**Comment by SashaCX75** [comment]
嘗試更改12小時格式的撥號盤的創建。 檢查是否有幫助。

我還注意到，在官方錶盤中，使用4張圖像顯示AM / PM索引。

Попробовал изменить создание циферблатов в 12 часовом формате. Проверяй, помогло или нет. 

Еще обратил внимание что в официальных циферблатах для отображения AM/PM индексов используется 4 изображения.

https://github.com/SashaCX75/AmazFit_Watchface_Editor/releases/tag/v8.5-beta

**Comment by kyle208** [comment]
![image](https://user-images.githubusercontent.com/12055155/91781460-f3218d80-ec2c-11ea-85e0-58ea753f3228.png)
![image](https://user-images.githubusercontent.com/12055155/91781472-f7e64180-ec2c-11ea-8a96-fee0a8973cb9.png)
我不喜欢AM/PM，所以没太注意，确实官方里是2个AM/PM，前中文后英文，我会和那些喜欢AMPM的人说弄2个的。（在1个AM/PM还是老的显示错误）
I don’t like AM/PM, so I didn’t pay too much attention to it. Indeed, there are 2 AM/PM in the official website, the first Chinese is the English, I will talk to those who like AMPM. (In 1 AM/PM or old display error)
Я не люблю AM / PM, поэтому особо не обращал на это внимания. Действительно, на официальном сайте 2 AM / PM, первый китайский - английский, поговорю с любителями AMPM. (В 1 AM / PM или старая ошибка дисплея)
