### ISSUE TITLE
GTS_Watch_face - Only Russian

### ISSUE THREAD

**Issue by bovirus** [SashaCX75/AmazFit_Watchface_Editor#35]
@SashaCX75 

Is it normal that strings in

https://github.com/SashaCX75/AmazFit_Watchface_Editor/tree/dev/GTS_Watch_face

are only in Russian (no English and no other languages)?

**Comment by SashaCX75** [comment]
Да это нормально.
Проекты GTS_Watch_face, WatchFace_PackUnpack, WatchFace_PackUnpack_for_GTS устарели и были объединены в один проект GTR_Watch_face

**Comment by bovirus** [comment]
@SashaCX75 

**English translation**
Yes, it is normal.
The GTS_Watch_face, WatchFace_PackUnpack, WatchFace_PackUnpack_for_GTS projects are deprecated and have been merged into one GTR_Watch_face project

If you can and you don't need please consider to remove GTS_Wtach_face folder.
