### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by bovirus** [SashaCX75/AmazFit_Watchface_Editor#44]
@SashaCX75 

I have soem reqeust about translation
Please check screenshot

![image](https://user-images.githubusercontent.com/1262554/105576236-b6883700-5d71-11eb-9d74-2772bbaf9719.png)

The string highlighted is in Russian and seems not included in language file (I didn't find it).

**Comment by bovirus** [comment]
@SashaCX75 

In FormFielExist in russain langaueg two strings are not available. 
What's the matter?

![image](https://user-images.githubusercontent.com/1262554/105576278-fea75980-5d71-11eb-91db-8a95776ee2aa.png)

**Comment by bovirus** [comment]
@SashaCX75 

In this screenshot the path is in Russian language (Administrator)?
What patrh is?

![image](https://user-images.githubusercontent.com/1262554/105576335-55149800-5d72-11eb-98ae-9938ab69ee88.png)

**Comment by bovirus** [comment]
@SashaCX75 

Could be possible to fill in in Italian langauge file the strings that are not translated (ex. equal to English) with the same text of English.

It can help when you release a new translation to see the new empty strings (beacuse are new).

Now in the Italian language there are many empty strings (empty why eqwual to English).

Then when you release a new language file have to scroll all strings to identify the empty strings that are equal to English from empty strings because are new strings.

If I will fillin empty because are equal English in teh future weill eb asy to dientify new empty strings.

**Comment by SashaCX75** [comment]
Отображение элементов (Displaying items) - write a translation here and I will add it to the program.

**Comment by SashaCX75** [comment]
You have some kind of mistake. These lines must be in the FormAnimation file, therefore there is no Russian text in them. I will transfer the Italian translation from these lines to the right place.

**Comment by bovirus** [comment]
@SashaCX75 

Thanks for teh fix about FormAnimation.

Please check othe post to check if it's normal 

path with Russian characters and Path is strange for Windows - normally is C:\Programfiles\users\xxxxx\... where xx is the user name).

**Comment by SashaCX75** [comment]
HelpProvider does not require translation. The necessary information is substituted in the program code.

**Comment by SashaCX75** [comment]
![2021-01-23_14-49-39](https://user-images.githubusercontent.com/12464527/105578708-b9435600-5d8a-11eb-89f8-aebfb4825a95.png)
Here is the line that you did not find. She just doesn't have an English translation yet.

**Comment by bovirus** [comment]
@SashaCX75 

Thansk for the info.
it's a bij job to scroll and find empty string (why equal to English and elave empty) then empty strings because are new strings added and not translated.

Are there problems if I wiil fill in the currently empty string (with value equal to English) and not leave them empty?

Then in the future will be easy to find new strings.

**Comment by bovirus** [comment]
@SashaCX75 

Please remind to fix the issues about strings in FormAnimation file.

**Comment by SashaCX75** [comment]
![2021-01-23_16-51-58](https://user-images.githubusercontent.com/12464527/105594663-e64c3480-5d9b-11eb-927b-c7722464c6a6.png)
If you want to temporarily add English phrases as a translation and then update them into Italian, this will not affect the program's operation. If that's more convenient for you, then you can.

But it seems to me that it is easier to leave them empty, and then filter out empty lines and add a translation. Moreover, there is not always an English translation. An example of such a case is shown in the screenshot.

I tried to indicate in the comments in the deadline whether its translation is required (after all, not everything needs to be translated). But such comments disappeared after updating the translation.

**Comment by SashaCX75** [comment]
I think this will be the last update of the program.

**Comment by SashaCX75** [comment]
Check the translation
https://github.com/SashaCX75/AmazFit_Watchface_Editor/releases/tag/v10.0-beta

**Comment by bovirus** [comment]
@SashaCX75 

About v. 10.0 beta seems all OK:
Thanks.
