### ISSUE TITLE
GTS animation (beta)

### ISSUE THREAD

**Issue by kyle208** [SashaCX75/AmazFit_Watchface_Editor#8]
Relay on behalf of users：GTS
Try to decompress the bin file of the green LCD digital dial, add a preview picture, repack it, upload it to GTS, and there will be a number that can't display a certain position normally, or simply cause GTS to restart continuously. I have tried to "decompress - add preview picture - pack" several times in a period of time, which is abnormal.

Later, I simply try to decompress the bin file of the green LCD digital dial, and then pack it again without changing anything. The result uploaded to GTS is still abnormal, or the number at a certain position can't be displayed normally. GTS is restarted. Once, GTS vibrates continuously. Finally, it can only be restarted after connecting the charging line for a while.

Can we judge that the compiled software may not be perfect enough?

GTS用户说：尝试把这个绿色液晶数字表盘的BIN文件解压，加上一张Preview图片后，重新打包，上传到GTS上面，就出现了不能正常显示某个位置的数字了，或者干脆导致GTS不断重启了，我在一段时间内，试过几次这样“解压-加Preview图片-打包”，都是有异常。

后来，我干脆作如此尝试：把这个绿色液晶数字表盘的BIN文件解压，然后什么都没有改变，直接再次打包。上传到GTS上面的结果，还是出现异常情况，还是某个位置的数字不能正常显示，GTS重启，有一次还出现了GTS不停震动，最后只能接上充电线一会儿才能重启。

这是不是可以判断，这编译软件有可能不够完善？

GTS BIN file:
[https://bbs.huami.com/forum.php?mod=attachment&aid=MzUzMjh8ZjdjYzgxNjB8MTU4NjI2ODgzNnwzMTE2MXwzOTQ0Mg%3D%3D](url)

**Comment by SashaCX75** [comment]
I have no way to test on GTS. On GTR 47, everything works fine. I can assume that the problem arises from the large file size. The bin file size is 1.49MB. If you add a preview image, then perhaps the size will exceed the permissible 1.5MB.

The editor uses third-party software to package the bin file and it may not be ideal. But I do not know better software for receiving bin files.

У меня нет возможности тестировать на GTS. На GTR 47 все работает нормально. Могу предположить, что проблемму возникают из за большого размера файла. Размер bin файла 1,49МБ. Если добавить картинку предпросмотра, то возможно размер превысит допустимый 1,5МБ.

В редакторе используется стороннее програмное обеспесение для запаковки  bin файла и оно может быть не идеальным. Но я не знаю более лучшего програмного обеспечения для получения bin фалов.

**Comment by kyle208** [comment]
Thanks for your reply.

**Comment by kyle208** [comment]
GTS dial animation (beta), too small window, incomplete text display.(editing->animation (beta)->animation preview animation->reset animation&save animation)

Анимация циферблата GTS (beta), окно слишком маленькое, текст не полный.(Правка - > анимация (beta) - > анимационный предварительный просмотр - > сброс анимации и сохранение анимации)

**Comment by SashaCX75** [comment]
@kyle208 
Where exactly is the incomplete text and in what language? On the buttons? I have all the text fit completely.
![2020-04-07_21-12-56](https://user-images.githubusercontent.com/12464527/78704558-b1f2af00-7914-11ea-807b-dc2d95a911de.png)

**Comment by kyle208** [comment]
Это может быть связано с разрешением монитора. Экран моего ноутбука (экран с высоким разрешением) ненормальный. Сегодня можно попробовать настольный компьютер. Это не должно быть программной проблемой. извините
可能跟显示器分辨率有关，我的笔记本电脑（高分屏）显示不正常，今天试了台式电脑是正常的，应该不是软件问题。抱歉

**Comment by SashaCX75** [comment]
@kyle208 
I think I understand what you're talking about. Problems arise when the font size is 125%.
Кажется я понял о чем ты говоришь. Проблемы возникают когда масштаб шрифта 125%.

**Comment by kyle208** [comment]
> @ kyle208
> 我想我明白您在说什么。字体大小为125％时会出现问题。
> Кажетсяяпонялочемтыговоришь。Проблемывозникаюткогдамасштабшрифта125％。

YES

**Comment by SashaCX75** [comment]
Changed display at font size 125%.

**Comment by kyle208** [comment]
![image](https://user-images.githubusercontent.com/12055155/79046639-cb616700-7c44-11ea-9975-02b55b9471ee.png)


> Changed display at font size 125%.
![image](https://user-images.githubusercontent.com/12055155/79046648-d4523880-7c44-11ea-8b99-0536b3d2abc7.png)
И здесь тоже.       choose->all valuse       выбор - > все значения

**Comment by SashaCX75** [comment]
Fixed in new version

**Comment by kyle208** [comment]
> Fixed in new version
大神，还有个问题，GTR实时温度能显示，夜间和日间温度却无法显示，软件里都设置对的，打包出来却没反应
Боже, все еще есть проблема. Температура GTR в реальном времени может отображаться, но температура ночью и днем не может быть отображена. Программное обеспечение настроено вправо, но оно не отвечает при упаковке.Я проверял это сам
![image](https://user-images.githubusercontent.com/12055155/79062420-c811be00-7ccc-11ea-834e-a6e42e4fff24.png)

**Comment by SashaCX75** [comment]
Day / night temperature is displayed only if it was not possible to obtain data on the current temperature from the server. I will probably add a warning about this somewhere in the program.

Температура день / ночь отображается только если не удалось получить данные о текущей температуре с сервера. Наверно добавлю предупреждение об этом гдето в программе.

**Comment by kyle208** [comment]
> Day / night temperature is displayed only if it was not possible to obtain data on the current temperature from the server. I will probably add a warning about this somewhere in the program.
> 
> Температура день / ночь отображается только если не удалось получить данные о текущей температуре с сервера. Наверно добавлю предупреждение об этом гдето в программе.
无法同时显示3个温度吗（最高最低当前温度）？
Невозможно отобразить 3 температуры одновременно (самая высокая и самая низкая текущая температура)？

**Comment by SashaCX75** [comment]
As far as I know, no. I have not seen any such dials.

**Comment by kyle208** [comment]
> As far as I know, no. I have not seen any such dials.

大神，可以上传新版本了吗，releases版本太老了。等了好久还没更新新的呢。
бог, можно загрузить новую версию, версия releases слишком старая.давно не обновлялась.

**Comment by kyle208** [comment]
大神，能否增加一个缩小窗口的选项，只有个关闭很不方便。
Великий Бог, можно ли добавить опцию, чтобы уменьшить окно, только одно закрытие очень неудобно.
![image](https://user-images.githubusercontent.com/12055155/79425569-77fc6980-7ff4-11ea-9ed1-8d9417a603c2.png)

**Comment by SashaCX75** [comment]
@kyle208 
Добавил кнопку сворачивания окна.
В новой версии появились новые фразы которые пока не переведены на китайский.
在窗口中添加了最小化按鈕。
新版本具有尚未翻譯成中文的新短語。
